# Generated by Django 5.2.4 on 2025-07-28 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='is_varified',
            new_name='is_verified',
        ),
    ]
