# Generated by Django 5.2.4 on 2025-08-12 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_rename_is_varified_userinfo_is_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('link', models.URLField(blank=True, max_length=250, null=True)),
                ('image', models.FileField(default=None, max_length=250, null=True, upload_to='images/')),
            ],
        ),
    ]
